/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_8 (
    input [5:0] alufn_signal,
    input v,
    input z,
    input n,
    output reg [31:0] cmp1
  );
  
  
  
  reg cmp;
  
  always @* begin
    
    case (alufn_signal[1+1-:2])
      2'h1: begin
        cmp = z;
      end
      2'h2: begin
        cmp = n ^ v;
      end
      2'h3: begin
        cmp = z | (n ^ v);
      end
      default: begin
        cmp = 1'h0;
      end
    endcase
    cmp1[2+29-:30] = 30'h00000000;
    cmp1[1+0-:1] = cmp;
    cmp1[0+0-:1] = 1'h0;
  end
endmodule
