/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux_2_10 (
    input s0,
    input [1:0] in,
    output reg out
  );
  
  
  
  always @* begin
    
    case (s0)
      1'h0: begin
        out = in[0+0-:1];
      end
      1'h1: begin
        out = in[1+0-:1];
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
