/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module muxfour_9 (
    input s0,
    input s1,
    input [3:0] in,
    output reg out
  );
  
  
  
  always @* begin
    
    case ({s1, s0})
      2'h0: begin
        out = in[0+0-:1];
      end
      2'h1: begin
        out = in[1+0-:1];
      end
      2'h2: begin
        out = in[2+0-:1];
      end
      2'h3: begin
        out = in[3+0-:1];
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
