/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_6 (
    input [31:0] a,
    input [31:0] b,
    input [5:0] alufn_signal,
    output reg [31:0] shift
  );
  
  
  
  wire [32-1:0] M_shl32_shl;
  reg [32-1:0] M_shl32_a;
  reg [5-1:0] M_shl32_b;
  mshl32bit_13 shl32 (
    .a(M_shl32_a),
    .b(M_shl32_b),
    .shl(M_shl32_shl)
  );
  
  wire [32-1:0] M_rev32pre_out;
  reg [32-1:0] M_rev32pre_a;
  reg [1-1:0] M_rev32pre_rev;
  xbitreverse_14 rev32pre (
    .a(M_rev32pre_a),
    .rev(M_rev32pre_rev),
    .out(M_rev32pre_out)
  );
  
  wire [32-1:0] M_rev32post_out;
  reg [32-1:0] M_rev32post_a;
  reg [1-1:0] M_rev32post_rev;
  xbitreverse_14 rev32post (
    .a(M_rev32post_a),
    .rev(M_rev32post_rev),
    .out(M_rev32post_out)
  );
  
  wire [1-1:0] M_sra_mux_0_out;
  reg [2-1:0] M_sra_mux_0_in;
  mux_2_10 sra_mux_0 (
    .s0(alufn_signal[1+0-:1]),
    .in(M_sra_mux_0_in),
    .out(M_sra_mux_0_out)
  );
  
  wire [1-1:0] M_sra_mux_1_out;
  reg [2-1:0] M_sra_mux_1_in;
  mux_2_10 sra_mux_1 (
    .s0(alufn_signal[1+0-:1]),
    .in(M_sra_mux_1_in),
    .out(M_sra_mux_1_out)
  );
  
  always @* begin
    M_sra_mux_0_in[0+0-:1] = a[31+0-:1];
    M_sra_mux_0_in[1+0-:1] = 1'h0;
    M_sra_mux_1_in[0+0-:1] = M_rev32post_out[31+0-:1];
    M_sra_mux_1_in[1+0-:1] = a[31+0-:1];
    M_rev32pre_rev = alufn_signal[0+0-:1];
    M_rev32post_rev = alufn_signal[0+0-:1];
    M_rev32pre_a[31+0-:1] = M_sra_mux_0_out;
    M_rev32pre_a[0+30-:31] = a[0+30-:31];
    M_shl32_b = b[0+4-:5];
    M_shl32_a = M_rev32pre_out;
    M_rev32post_a = M_shl32_shl;
    shift[31+0-:1] = M_sra_mux_1_out;
    shift[0+30-:31] = M_rev32post_out[0+30-:31];
  end
endmodule
