/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mshl32bit_13 (
    input [31:0] a,
    input [4:0] b,
    output reg [31:0] shl
  );
  
  
  
  wire [32-1:0] M_s16l_out;
  reg [32-1:0] M_s16l_a;
  x_bit_left_shifter_16 s16l (
    .shift(b[4+0-:1]),
    .a(M_s16l_a),
    .out(M_s16l_out)
  );
  
  wire [32-1:0] M_s8l_out;
  reg [32-1:0] M_s8l_a;
  x_bit_left_shifter_17 s8l (
    .shift(b[3+0-:1]),
    .a(M_s8l_a),
    .out(M_s8l_out)
  );
  
  wire [32-1:0] M_s4l_out;
  reg [32-1:0] M_s4l_a;
  x_bit_left_shifter_18 s4l (
    .shift(b[2+0-:1]),
    .a(M_s4l_a),
    .out(M_s4l_out)
  );
  
  wire [32-1:0] M_s2l_out;
  reg [32-1:0] M_s2l_a;
  x_bit_left_shifter_19 s2l (
    .shift(b[1+0-:1]),
    .a(M_s2l_a),
    .out(M_s2l_out)
  );
  
  wire [32-1:0] M_s1l_out;
  reg [32-1:0] M_s1l_a;
  x_bit_left_shifter_20 s1l (
    .shift(b[0+0-:1]),
    .a(M_s1l_a),
    .out(M_s1l_out)
  );
  
  always @* begin
    M_s16l_a = a;
    M_s8l_a = M_s16l_out;
    M_s4l_a = M_s8l_out;
    M_s2l_a = M_s4l_out;
    M_s1l_a = M_s2l_out;
    shl = M_s1l_out;
  end
endmodule
