/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplier_7 (
    input [31:0] a,
    input [31:0] b,
    output reg [31:0] mul
  );
  
  
  
  integer i;
  integer j;
  
  integer previous_row_fa_index;
  
  integer current_row_fa_index;
  
  wire [(9'h1f0+0)-1:0] M_fa_s;
  wire [(9'h1f0+0)-1:0] M_fa_co;
  reg [(9'h1f0+0)-1:0] M_fa_a;
  reg [(9'h1f0+0)-1:0] M_fa_b;
  reg [(9'h1f0+0)-1:0] M_fa_ci;
  
  genvar GEN_fa0;
  generate
  for (GEN_fa0=0;GEN_fa0<9'h1f0;GEN_fa0=GEN_fa0+1) begin: fa_gen_0
    full_adder_15 fa (
      .a(M_fa_a[GEN_fa0*(1)+(1)-1-:(1)]),
      .b(M_fa_b[GEN_fa0*(1)+(1)-1-:(1)]),
      .ci(M_fa_ci[GEN_fa0*(1)+(1)-1-:(1)]),
      .s(M_fa_s[GEN_fa0*(1)+(1)-1-:(1)]),
      .co(M_fa_co[GEN_fa0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  always @* begin
    mul[0+0-:1] = a[0+0-:1] & b[0+0-:1];
    for (i = 1'h0; i < 5'h1f; i = i + 1) begin
      M_fa_a[(i)*1+0-:1] = a[(i)*1+0-:1] & b[1+0-:1];
      M_fa_b[(i)*1+0-:1] = a[(i + 1'h1)*1+0-:1] & b[0+0-:1];
      if (i == 1'h0) begin
        M_fa_ci[(i)*1+0-:1] = 1'h0;
      end else begin
        M_fa_ci[(i)*1+0-:1] = M_fa_co[(i - 1'h1)*1+0-:1];
      end
    end
    mul[1+0-:1] = M_fa_s[0+0-:1];
    previous_row_fa_index = 1'h0;
    current_row_fa_index = 5'h1f;
    for (i = 2'h2; i < 6'h20; i = i + 1) begin
      for (j = 1'h0; j < 6'h20 - i; j = j + 1) begin
        M_fa_a[(current_row_fa_index + j)*1+0-:1] = a[(j)*1+0-:1] & b[(i)*1+0-:1];
        M_fa_b[(current_row_fa_index + j)*1+0-:1] = M_fa_s[(previous_row_fa_index + j + 1'h1)*1+0-:1];
        if (j == 1'h0) begin
          M_fa_ci[(current_row_fa_index + j)*1+0-:1] = 1'h0;
        end else begin
          M_fa_ci[(current_row_fa_index + j)*1+0-:1] = M_fa_co[(current_row_fa_index + j - 1'h1)*1+0-:1];
        end
      end
      previous_row_fa_index = current_row_fa_index;
      current_row_fa_index = current_row_fa_index + j;
      mul[(i)*1+0-:1] = M_fa_s[(previous_row_fa_index)*1+0-:1];
    end
  end
endmodule
