/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     NBITS = 32
*/
module xbitreverse_14 (
    input [31:0] a,
    input rev,
    output reg [31:0] out
  );
  
  localparam NBITS = 6'h20;
  
  
  wire [(6'h20+0)-1:0] M_muxes_out;
  reg [(6'h20+0)-1:0] M_muxes_s0;
  reg [(6'h20+0)*2-1:0] M_muxes_in;
  
  genvar GEN_muxes0;
  generate
  for (GEN_muxes0=0;GEN_muxes0<6'h20;GEN_muxes0=GEN_muxes0+1) begin: muxes_gen_0
    mux_2_10 muxes (
      .s0(M_muxes_s0[GEN_muxes0*(1)+(1)-1-:(1)]),
      .in(M_muxes_in[GEN_muxes0*(2'h2)+(2'h2)-1-:(2'h2)]),
      .out(M_muxes_out[GEN_muxes0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  integer n;
  
  always @* begin
    M_muxes_s0 = rev;
    for (n = 1'h0; n < 6'h20; n = n + 1) begin
      M_muxes_in[(n)*2+0+0-:1] = a[(n)*1+0-:1];
      M_muxes_in[(7'h1f - n)*2+1+0-:1] = a[(n)*1+0-:1];
    end
    out = M_muxes_out;
  end
endmodule
